# Generated by Django 5.1.4 on 2024-12-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='job_type',
        ),
    ]
