# Generated by Django 5.1.4 on 2024-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_job_title_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
